//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnotationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annotation
    {
        public Annotation()
        {
            this.AnnotationDetails = new HashSet<AnnotationDetail>();
        }
    
        public int annotation_ID { get; set; }
        public Nullable<int> video_ID { get; set; }
    
        public virtual ICollection<AnnotationDetail> AnnotationDetails { get; set; }
        public virtual Video Video { get; set; }
    }
}
