//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnotationApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnnotationDBEntities : DbContext
    {
        public AnnotationDBEntities()
            : base("name=AnnotationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnnotationDetail> AnnotationDetails { get; set; }
        public DbSet<Annotation> Annotations { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<VideoDetail> VideoDetails { get; set; }
        public DbSet<Video> Videos { get; set; }
    }
}
