//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnotationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.AnnotationDetails = new HashSet<AnnotationDetail>();
        }
    
        public int group_ID { get; set; }
        public string group_Name { get; set; }
        public string persons { get; set; }
    
        public virtual ICollection<AnnotationDetail> AnnotationDetails { get; set; }
    }
}
